micronaut.server.port=8095
app.version=@project.version@

# Enable CORS
micronaut.server.cors.enabled=true
micronaut.server.cors.configurations.webstable.allowed-origins[0]=http://localhost:5173
micronaut.server.cors.configurations.webstable.allowed-methods[0]=GET
micronaut.server.cors.configurations.webstable.allowed-methods[1]=OPTIONS
micronaut.server.cors.configurations.webstable.allowed-headers[0]=Content-Type
micronaut.server.cors.configurations.webstable.allowed-headers[1]=Accept
micronaut.server.cors.configurations.webstable.allowed-headers[2]=Authorization
